export const seedCategories = [
	{ slug: 'fooldal', name: 'Főoldal' },
	{ slug: 'minden', name: 'Minden' },
	{ slug: 'egyeb', name: 'Egyéb' },
	{ slug: 'belfold', name: 'Belföld' },
	{ slug: 'kulfold', name: 'Külföld' },
	{ slug: 'gazdasag', name: 'Gazdaság' },
	{ slug: 'tech', name: 'Tech' },
	{ slug: 'sport', name: 'Sport' },
	{ slug: 'bulvar', name: 'Bulvár' },
	{ slug: 'eletmod', name: 'Életmód' },
	{ slug: 'auto', name: 'Autó' },
	{ slug: 'top50', name: 'Top50' }
];

export const seedSources = [
	{ slug: '168-hu', name: '168.hu', domain: '168.hu' },
	{ slug: '24-hu', name: '24.hu', domain: '24.hu' },
	{ slug: '444-hu', name: '444.hu', domain: '444.hu' },
	{ slug: 'acnews', name: 'ACNews', domain: 'acnews.hu' },
	{ slug: 'agroinform', name: 'Agroinform', domain: 'agroinform.hu' },
	{ slug: 'atv', name: 'ATV', domain: 'atv.hu' },
	{ slug: 'autoszektor', name: 'Autószektor', domain: 'autoszektor.hu' },
	{ slug: 'autopro', name: 'Autópro', domain: 'autopro.hu' },
	{ slug: 'bien', name: 'Bien', domain: 'bien.hu' },
	{ slug: 'bitport', name: 'BitPort', domain: 'bitport.hu' },
	{ slug: 'blikk', name: 'Blikk', domain: 'blikk.hu' },
	{ slug: 'ruzs-online', name: 'Rúzs Online', domain: 'blikkruzs.blikk.hu' },
	{ slug: 'colore', name: 'Colore', domain: 'colore.hu' },
	{ slug: 'csakfoci', name: 'CsakFoci', domain: 'csakfoci.hu' },
	{ slug: 'demokrata', name: 'Demokrata', domain: 'demokrata.hu' },
	{ slug: 'divany', name: 'Dívány', domain: 'divany.hu' },
	{ slug: 'economx', name: 'Economx', domain: 'economx.hu' },
	{ slug: 'egeszsegkalauz', name: 'Egészségkalauz', domain: 'egeszsegkalauz.hu' },
	{ slug: 'elle', name: 'Elle', domain: 'elle.hu' },
	{ slug: 'f1vilag', name: 'F1világ', domain: 'f1vilag.hu' },
	{ slug: 'femcafe', name: 'Femcafe', domain: 'femcafe.hu' },
	{ slug: 'femina', name: 'Femina', domain: 'femina.hu' },
	{ slug: 'forbes', name: 'Forbes', domain: 'forbes.hu' },
	{ slug: 'glamour', name: 'Glamour', domain: 'glamour.hu' },
	{ slug: 'haszon', name: 'Haszon', domain: 'haszon.hu' },
	{ slug: 'hazipatika', name: 'Házipatika', domain: 'hazipatika.com' },
	{ slug: 'hellomagyar', name: 'Hellomagyar', domain: 'hellomagyar.hu' },
	{ slug: 'hir-tv', name: 'Hír TV', domain: 'hirtv.hu' },
	{ slug: 'hrportal', name: 'HRportal', domain: 'hrportal.hu' },
	{ slug: 'hup', name: 'Hup', domain: 'hup.hu' },
	{ slug: 'hvg', name: 'hvg.hu', domain: 'hvg.hu' },
	{ slug: 'hwsw', name: 'HWSW', domain: 'hwsw.hu' },
	{ slug: 'index', name: 'Index', domain: 'index.hu' },
	{ slug: 'infostart', name: 'Infostart', domain: 'infostart.hu' },
	{ slug: 'instyle', name: 'InStyle', domain: 'instyle.hu' },
	{ slug: 'itbusiness', name: 'ITBusiness', domain: 'itbusiness.hu' },
	{ slug: 'kiskegyed', name: 'Kiskegyed', domain: 'kiskegyed.hu' },
	{ slug: 'klubradio', name: 'Klubrádió', domain: 'klubradio.hu' },
	{ slug: 'kontroll', name: 'Kontroll.hu', domain: 'kontroll.hu' },
	{ slug: 'liner', name: 'Liner', domain: 'liner.hu' },
	{ slug: 'magyarhang', name: 'MagyarHang', domain: 'hang.hu' },
	{ slug: 'magyarhirlap', name: 'MagyarHírlap', domain: 'magyarhirlap.hu' },
	{ slug: 'magyarnemzet', name: 'MagyarNemzet', domain: 'magyarnemzet.hu' },
	{ slug: 'mandiner', name: 'Mandiner', domain: 'mandiner.hu' },
	{ slug: 'mediapiac', name: 'MédiaPiac', domain: 'mediapiac.com' },
	{ slug: 'metropol', name: 'Metropol', domain: 'metropol.hu' },
	{ slug: 'mfor', name: 'Mfor', domain: 'mfor.hu' },
	{ slug: 'motorsport', name: 'MotorSport', domain: 'motorsport.hu' },
	{ slug: 'magyarnarancs', name: 'Magyar Narancs', domain: 'magyarnarancs.hu' },
	{ slug: 'nb1', name: 'NB1', domain: 'nb1.hu' },
	{ slug: 'nepszava', name: 'Népszava', domain: 'nepszava.hu' },
	{ slug: 'nlc', name: 'NLC', domain: 'nlc.hu' },
	{ slug: 'origo', name: 'Origo', domain: 'origo.hu' },
	{ slug: 'penzcentrum', name: 'Pénzcentrum', domain: 'penzcentrum.hu' },
	{ slug: 'piac-es-profit', name: 'Piac és Profit', domain: 'piacesprofit.hu' },
	{ slug: 'player', name: 'Player', domain: 'player.hu' },
	{ slug: 'portfolio', name: 'Portfólió', domain: 'portfolio.hu' },
	{ slug: 'privatbankar', name: 'Privátbankár.hu', domain: 'privatbankar.hu' },
	{ slug: 'profitline', name: 'ProfitLine', domain: 'profitline.hu' },
	{ slug: 'prohardver', name: 'Prohardver', domain: 'prohardver.hu' },
	{ slug: 'promotions', name: 'Promotions', domain: 'promotions.hu' },
	{ slug: 'propeller', name: 'Propeller', domain: 'propeller.hu' },
	{ slug: 'sg', name: 'SG', domain: 'sg.hu' },
	{ slug: 'sportposzt', name: 'Sportposzt', domain: 'sportposzt.hu' },
	{ slug: 'szeretlek-magyarorszag', name: 'Szeretlek Mo.', domain: 'szeretlekmagyarorszag.hu' },
	{ slug: 'telex', name: 'Telex', domain: 'telex.hu' },
	{ slug: 'termalonline', name: 'TermálOnline', domain: 'termalonline.hu' },
	{ slug: 'totalcar', name: 'Totalcar', domain: 'totalcar.hu' },
	{ slug: 'uzletem', name: 'Üzletem', domain: 'uzletem.hu' },
	{ slug: 'vezess', name: 'Vezess', domain: 'vezess.hu' },
	{ slug: 'vg', name: 'VG', domain: 'vg.hu' },
	{ slug: 'villanyautosok', name: 'Villanyautósok', domain: 'villanyautosok.hu' },
	{ slug: 'wmn', name: 'WMN', domain: 'wmn.hu' }
];

export const seedFeeds = [
	{
		source: { slug: 'telex', name: 'Telex', domain: 'telex.hu' },
		feedUrl: 'https://telex.hu/rss',
		categorySlug: 'minden'
	},
	{
		source: { slug: '24-hu', name: '24.hu', domain: '24.hu' },
		feedUrl: 'https://24.hu/feed/',
		categorySlug: 'minden'
	},
	{
		source: { slug: 'hvg', name: 'HVG', domain: 'hvg.hu' },
		feedUrl: 'https://hvg.hu/rss',
		categorySlug: 'minden'
	},
	{
		source: { slug: 'index', name: 'Index', domain: 'index.hu' },
		feedUrl: 'https://index.hu/24ora/rss/',
		categorySlug: 'minden'
	},
	{
		source: { slug: 'portfolio', name: 'Portfolio', domain: 'portfolio.hu' },
		feedUrl: 'https://www.portfolio.hu/rss/all.xml',
		categorySlug: 'gazdasag'
	}
];
